"""
F1 Live Timing Log Extractor

This module provides functions to extract and analyze information from F1 live timing log files
generated by the SignalF1 client.
"""

import ast
import base64
import json
import re
import zlib
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


@dataclass()
class LogEntry:
  """Represents a single log entry from the F1 timing log."""

  timestamp: datetime
  level: str
  message: str
  raw_data: dict | None = None


@dataclass()
class SessionInfo:
  """Basic session information extracted from the log."""

  session_start: datetime | None = None
  session_end: datetime | None = None
  total_messages: int = 0
  connection_url: str | None = None
  websocket_url: str | None = None
  connection_id: str | None = None
  session_type: str | None = None
  meeting_name: str | None = None
  location: str | None = None


@dataclass()
class DriverInfo:
  """Driver information from the log."""

  racing_number: str
  broadcast_name: str
  full_name: str
  tla: str  # Three-letter abbreviation
  team_name: str
  team_colour: str
  first_name: str
  last_name: str


@dataclass()
class TimingData:
  """Timing data for a specific moment."""

  timestamp: datetime
  driver_data: dict[str, Any]  # Racing number -> timing info


def _parse_jsonish_payload(payload: str) -> dict[str, Any] | list[Any] | None:
  try:
    return json.loads(payload)
  except json.JSONDecodeError:
    try:
      return ast.literal_eval(payload)
    except (SyntaxError, ValueError):
      return None


def _parse_server_timestamp(value: Any) -> datetime | None:
  if not isinstance(value, str) or not value:
    return None

  try:
    return datetime.fromisoformat(value.replace("Z", "+00:00"))
  except ValueError:
    return None


def _extract_timestamp_from_raw(raw_data: dict[str, Any]) -> datetime | None:
  messages = raw_data.get("M", [])
  for msg in messages:
    if msg.get("H") != "Streaming" or msg.get("M") != "feed":
      continue

    args = msg.get("A", [])
    if len(args) >= 3:
      parsed = _parse_server_timestamp(args[2])
      if parsed is not None:
        return parsed

  return None


def _parse_data_line(line: str) -> LogEntry | None:
  payload = line.strip()
  if not payload:
    return None

  if payload[0] not in "[{":
    for marker in (",[", ",{"):
      marker_index = payload.find(marker)
      if marker_index != -1:
        payload = payload[marker_index + 1 :]
        break
    else:
      return None

  parsed = _parse_jsonish_payload(payload)
  if isinstance(parsed, dict):
    timestamp = _extract_timestamp_from_raw(parsed)
    if timestamp is None:
      return None
    return LogEntry(timestamp=timestamp, level="DATA", message=line.strip(), raw_data=parsed)

  if isinstance(parsed, (list, tuple)) and len(parsed) == 3 and isinstance(parsed[0], str):
    timestamp = _parse_server_timestamp(parsed[2])
    if timestamp is None:
      return None
    raw_data = {"M": [{"H": "Streaming", "M": "feed", "A": list(parsed)}]}
    return LogEntry(timestamp=timestamp, level="DATA", message=line.strip(), raw_data=raw_data)

  return None


def parse_log_file(log_path: str) -> list[LogEntry]:
  """
  Parse a SignalF1 file and extract normalized entries.

  Supports both telemetry JSONL output and legacy application logs.

  Args:
      log_path: Path to the log file

  Returns:
      list of LogEntry objects
  """
  entries = []
  log_pattern = re.compile(r"^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - (\w+): (.+)$")

  with open(log_path, "r", encoding="utf-8") as f:
    for line in f:
      line = line.strip()
      if not line:
        continue

      match = log_pattern.match(line)
      if match:
        timestamp_str, level, message = match.groups()
        timestamp = datetime.strptime(timestamp_str, "%Y-%m-%d %H:%M:%S,%f")

        # Try to parse JSON data from the message
        raw_data = None
        if message.startswith("Received raw message: "):
          json_str = message[22:]  # Remove "Received raw message: " prefix
          if json_str and json_str != "{}":
            try:
              raw_data = json.loads(json_str)
            except json.JSONDecodeError:
              pass

        entries.append(LogEntry(timestamp=timestamp, level=level, message=message, raw_data=raw_data))
        continue

      parsed_entry = _parse_data_line(line)
      if parsed_entry is not None:
        entries.append(parsed_entry)

  return entries


def extract_session_info(entries: list[LogEntry]) -> SessionInfo:
  """
  Extract basic session information from log entries.

  Args:
      entries: list of log entries

  Returns:
      SessionInfo object with extracted data
  """
  info = SessionInfo()

  if entries:
    info.session_start = entries[0].timestamp
    info.session_end = entries[-1].timestamp
    info.total_messages = len([e for e in entries if e.raw_data])

  for entry in entries:
    # Extract connection information
    if "Negotiating SignalR connection to" in entry.message:
      match = re.search(r"to (https?://[^\s]+)", entry.message)
      if match:
        info.connection_url = match.group(1)

    # Extract WebSocket URL
    elif "WebSocket URL:" in entry.message:
      match = re.search(r"WebSocket URL: (wss?://[^\s]+)", entry.message)
      if match:
        info.websocket_url = match.group(1)

    # Extract connection ID
    elif "ConnectionId" in entry.message:
      match = re.search(r"'ConnectionId': '([^']+)'", entry.message)
      if match:
        info.connection_id = match.group(1)

    # Extract session data from feed messages
    elif entry.raw_data and "M" in entry.raw_data:
      messages = entry.raw_data.get("M", [])
      for msg in messages:
        if msg.get("H") == "Streaming" and msg.get("M") == "feed":
          args = msg.get("A", [])
          if len(args) >= 2:
            data_type, data = args[0], args[1]

            # Extract session info
            if data_type == "SessionInfo" and isinstance(data, dict):
              session_data = data.get("Meeting", {})
              info.meeting_name = session_data.get("Name")
              info.location = session_data.get("Location")
              info.session_type = data.get("Type")

  return info


def extract_driver_list(entries: list[LogEntry]) -> dict[str, DriverInfo]:
  """
  Extract driver information from the log entries.

  Args:
      entries: list of log entries

  Returns:
      dictionary mapping racing numbers to DriverInfo objects
  """
  drivers = {}

  for entry in entries:
    if entry.raw_data and "M" in entry.raw_data:
      messages = entry.raw_data.get("M", [])
      for msg in messages:
        if msg.get("H") == "Streaming" and msg.get("M") == "feed":
          args = msg.get("A", [])
          if len(args) >= 2:
            data_type, data = args[0], args[1]

            if data_type == "DriverList" and isinstance(data, dict):
              for racing_num, driver_data in data.items():
                if racing_num != "_kf" and isinstance(driver_data, dict):
                  drivers[racing_num] = DriverInfo(
                    racing_number=driver_data.get("RacingNumber", racing_num),
                    broadcast_name=driver_data.get("BroadcastName", ""),
                    full_name=driver_data.get("FullName", ""),
                    tla=driver_data.get("Tla", ""),
                    team_name=driver_data.get("TeamName", ""),
                    team_colour=driver_data.get("TeamColour", ""),
                    first_name=driver_data.get("FirstName", ""),
                    last_name=driver_data.get("LastName", ""),
                  )

  return drivers


def decompress_data(compressed_data: str) -> str | None:
  """
  Decompress base64-encoded, zlib-compressed data from F1 live timing.

  Args:
      compressed_data: Base64-encoded compressed data using raw deflate

  Returns:
      Decompressed string or None if decompression fails
  """
  try:
    # Decode base64
    decoded = base64.b64decode(compressed_data)
    # Decompress with zlib using raw deflate (-15 window bits)
    # F1 uses raw deflate compression without zlib headers
    decompressed = zlib.decompress(decoded, -15)
    return decompressed.decode("utf-8")
  except Exception:
    return None


def extract_timing_data(entries: list[LogEntry], limit: int = None) -> list[TimingData]:
  """
  Extract timing data from log entries.

  Args:
      entries: list of log entries
      limit: Maximum number of timing data points to extract (None for all)

  Returns:
      list of TimingData objects
  """
  timing_data = []
  count = 0

  for entry in entries:
    if limit and count >= limit:
      break

    if entry.raw_data and "M" in entry.raw_data:
      messages = entry.raw_data.get("M", [])
      for msg in messages:
        if msg.get("H") == "Streaming" and msg.get("M") == "feed":
          args = msg.get("A", [])
          if len(args) >= 2:
            data_type, data = args[0], args[1]

            if data_type == "TimingData" and isinstance(data, dict):
              lines = data.get("Lines", {})
              if lines:
                timing_data.append(TimingData(timestamp=entry.timestamp, driver_data=lines))
                count += 1
                break

  return timing_data


def extract_car_data(entries: list[LogEntry], limit: int = None) -> list[tuple[datetime, str]]:
  """
  Extract compressed car data from log entries.

  Args:
      entries: list of log entries
      limit: Maximum number of car data points to extract (None for all)

  Returns:
      list of tuples (timestamp, decompressed_data)
  """
  car_data = []
  count = 0

  for entry in entries:
    if limit and count >= limit:
      break

    if entry.raw_data and "M" in entry.raw_data:
      messages = entry.raw_data.get("M", [])
      for msg in messages:
        if msg.get("H") == "Streaming" and msg.get("M") == "feed":
          args = msg.get("A", [])
          if len(args) >= 2:
            data_type, data = args[0], args[1]

            if data_type == "CarData.z" and isinstance(data, str):
              decompressed = decompress_data(data)
              if decompressed:
                car_data.append((entry.timestamp, decompressed))
                count += 1
                break

  return car_data


def extract_heartbeats(entries: list[LogEntry]) -> list[tuple[datetime, str]]:
  """
  Extract heartbeat timestamps from the log.

  Args:
      entries: list of log entries

  Returns:
      list of tuples (local_timestamp, server_utc_timestamp)
  """
  heartbeats = []

  for entry in entries:
    if entry.raw_data and "M" in entry.raw_data:
      messages = entry.raw_data.get("M", [])
      for msg in messages:
        if msg.get("H") == "Streaming" and msg.get("M") == "feed":
          args = msg.get("A", [])
          if len(args) >= 2:
            data_type, data = args[0], args[1]

            if data_type == "Heartbeat" and isinstance(data, dict):
              server_utc = data.get("Utc", "")
              heartbeats.append((entry.timestamp, server_utc))
              break

  return heartbeats


def generate_log_summary(log_path: str) -> dict[str, Any]:
  """
  Generate a comprehensive summary of the F1 timing log file.

  Args:
      log_path: Path to the log file

  Returns:
      dictionary containing the extracted information
  """
  print(f"Parsing log file: {log_path}")
  entries = parse_log_file(log_path)

  print("Extracting session information...")
  session_info = extract_session_info(entries)

  print("Extracting driver information...")
  drivers = extract_driver_list(entries)

  print("Extracting timing data...")
  timing_data = extract_timing_data(entries, limit=10)  # First 10 timing updates

  print("Extracting car data...")
  car_data = extract_car_data(entries, limit=5)  # First 5 car data updates

  print("Extracting heartbeats...")
  heartbeats = extract_heartbeats(entries)

  # Count different message types
  message_types = {}
  for entry in entries:
    if entry.raw_data and "M" in entry.raw_data:
      messages = entry.raw_data.get("M", [])
      for msg in messages:
        if msg.get("H") == "Streaming" and msg.get("M") == "feed":
          args = msg.get("A", [])
          if args:
            data_type = args[0]
            message_types[data_type] = message_types.get(data_type, 0) + 1

  return {
    "file_path": log_path,
    "session_info": session_info,
    "drivers": drivers,
    "message_types": message_types,
    "total_entries": len(entries),
    "sample_timing_data": timing_data,
    "sample_car_data": [(ts.isoformat(), data[:100] + "..." if len(data) > 100 else data) for ts, data in car_data],
    "heartbeat_count": len(heartbeats),
    "first_heartbeat": heartbeats[0] if heartbeats else None,
    "last_heartbeat": heartbeats[-1] if heartbeats else None,
  }


def print_log_summary(summary: dict[str, Any]):
  """
  Print a formatted summary of the log analysis.

  Args:
      summary: Summary dictionary from generate_log_summary
  """
  print("\n" + "=" * 60)
  print("F1 LIVE TIMING LOG ANALYSIS")
  print("=" * 60)

  session = summary["session_info"]
  print("\nSESSION INFORMATION:")
  print(f"  Meeting: {session.meeting_name}")
  print(f"  Location: {session.location}")
  print(f"  Session Type: {session.session_type}")
  if session.session_start and session.session_end:
    duration = session.session_end - session.session_start
    print(f"  Duration: {duration}")
  print(f"  Start Time: {session.session_start}")
  print(f"  End Time: {session.session_end}")
  print(f"  Connection URL: {session.connection_url}")
  print(f"  Connection ID: {session.connection_id}")

  print("\nSTATISTICS:")
  print(f"  Total Log Entries: {summary['total_entries']}")
  print(f"  Total Messages: {session.total_messages}")
  print(f"  Heartbeats: {summary['heartbeat_count']}")

  drivers = summary["drivers"]
  print(f"\nDRIVERS ({len(drivers)}):")
  for racing_num, driver in sorted(drivers.items(), key=lambda x: int(x[0])):
    print(f"  #{racing_num}: {driver.full_name} ({driver.tla}) - {driver.team_name}")

  # Message types
  print("\nMESSAGE TYPES:")
  for msg_type, count in sorted(summary["message_types"].items()):
    print(f"  {msg_type}: {count}")

  # Sample timing data
  if summary["sample_timing_data"]:
    print("\nSAMPLE TIMING DATA:")
    for timing in summary["sample_timing_data"][:3]:
      print(f"  {timing.timestamp}: {len(timing.driver_data)} drivers")

  print("\n" + "=" * 60)


if __name__ == "__main__":
  # Example usage
  import sys

  if len(sys.argv) > 1:
    log_file = sys.argv[1]
  else:
    # Use the current log file as default
    log_file = r"c:\Users\david\projects\_\signalf1\data\raw\20250802_123439.log.log"

  if Path(log_file).exists():
    summary = generate_log_summary(log_file)
    print_log_summary(summary)
  else:
    print(f"Log file not found: {log_file}")
